version: '3.8'
services:
  web:
    build: .
    command: npx next start --host "::" --port 3000 # Railway requires binding to ipv6 address
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_EMAIL_HOSTS=${ALLOWED_EMAIL_HOSTS}
      - APP_URL=${APP_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
  worker:
    build: .
    command: node scripts/start-worker.mjs
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - WORKER_PROCESSING_INTERVAL=${WORKER_PROCESSING_INTERVAL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  rtdb:
    build: .
    command: node scripts/start-rtdb.mjs
    ports:
      - '4001:4001'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
  mail: # Development only mail server
    build: .
    command: node scripts/start-mail-server.mjs
    ports:
      - '1025:1025'
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=http://web:3000 # Internal network URL to access the web service API
