#!/bin/bash
# Better Auth Setup Script - Reference Commands

echo "================================================"
echo "  Better Auth Setup - Step by Step"
echo "================================================"
echo ""

echo "📋 STEP 1: Get Google OAuth Credentials"
echo "   1. Open: https://console.cloud.google.com/"
echo "   2. Create new project or select existing"
echo "   3. Enable Google+ API"
echo "   4. Create OAuth 2.0 Web credentials"
echo "   5. Add Authorized redirect URI:"
echo "      http://localhost:3000/api/auth/callback/google"
echo "   6. Copy Client ID and Client Secret"
echo ""

echo "✏️  STEP 2: Update .env File"
echo "   Edit .env and add:"
echo ""
echo "   GOOGLE_CLIENT_ID=your_client_id_here"
echo "   GOOGLE_CLIENT_SECRET=your_client_secret_here"
echo ""
echo "   Verify these are also set:"
echo "   APP_URL=http://localhost:3000"
echo "   NEXT_PUBLIC_APP_URL=http://localhost:3000"
echo "   MONGODB_URI=mongodb+srv://..."
echo "   DATABASE_NAME=production"
echo ""

echo "🚀 STEP 3: Start the Application"
echo ""
echo "   npm start"
echo ""
echo "   The app will start and you should see:"
echo "   - ✓ Ready in XXXms"
echo "   - ✓ Compiled / in XXXms"
echo ""

echo "🌐 STEP 4: Test in Browser"
echo ""
echo "   1. Open: http://localhost:3000"
echo "   2. You should see:"
echo "      - Welcome to Bento Mail"
echo "      - Sign in with Google button"
echo "   3. Click the button"
echo "   4. Sign in with your Google account"
echo "   5. You should be redirected to your bundle page"
echo ""

echo "🗄️  STEP 5: Verify MongoDB"
echo ""
echo "   After signing in, check MongoDB for:"
echo "   1. New user in 'users' collection"
echo "   2. New account in 'accounts' collection"
echo "   3. New session in 'sessions' collection"
echo ""

echo "📚 Documentation Files"
echo "   - QUICK_START.md           (this summary)"
echo "   - GETTING_STARTED.md       (setup guide)"
echo "   - BETTER_AUTH_COMPLETE.md  (comprehensive)"
echo "   - CHECKLIST.md             (verification)"
echo "   - docs/BETTER-AUTH-FIX.md  (what was fixed)"
echo ""

echo "🆘 Troubleshooting"
echo ""
echo "   Issue: Google sign-in doesn't work"
echo "   Solution: Check GOOGLE_CLIENT_ID/SECRET in .env"
echo "            Check redirect URI in Google Console"
echo ""
echo "   Issue: Can't find Collections in MongoDB"
echo "   Solution: They auto-create on first sign-in"
echo "            Check MongoDB connection is working"
echo ""
echo "   Issue: Session doesn't persist"
echo "   Solution: Check browser cookies (DevTools)"
echo "            Check MONGODB_URI and DATABASE_NAME"
echo ""

echo "✅ You're All Set!"
echo "   Implementation is complete and tested."
echo "   Just follow the 5 steps above."
echo ""
echo "================================================"
