// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma-next/adapter-mongo/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
} from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:ceebf4b3b7233b9192ee45010b1f14e7bd658bb1f307ae6f1096f5f87e11e39f'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:cca47cfb902adf4e15c2f277dd98af4aff64a3a2c010b49ace1c897de1cc4510'>;

export type CodecTypes = MongoCodecTypes;

export type SummariesOutput = {
  readonly oneliner: CodecTypes['mongo/string@1']['output'];
  readonly overview: CodecTypes['mongo/string@1']['output'];
  readonly details: CodecTypes['mongo/string@1']['output'];
};
export type SummariesInput = {
  readonly oneliner: CodecTypes['mongo/string@1']['input'];
  readonly overview: CodecTypes['mongo/string@1']['input'];
  readonly details: CodecTypes['mongo/string@1']['input'];
};
export type BasicArticleOutput = {
  readonly content: CodecTypes['mongo/string@1']['output'];
  readonly header: CodecTypes['mongo/string@1']['output'];
  readonly url: CodecTypes['mongo/string@1']['output'] | null;
  readonly date: CodecTypes['mongo/string@1']['output'] | null;
  readonly coverImg: CodecTypes['mongo/string@1']['output'] | null;
  readonly sourceName: CodecTypes['mongo/string@1']['output'] | null;
  readonly lastError: CodecTypes['mongo/string@1']['output'] | null;
};
export type BasicArticleInput = {
  readonly content: CodecTypes['mongo/string@1']['input'];
  readonly header: CodecTypes['mongo/string@1']['input'];
  readonly url: CodecTypes['mongo/string@1']['input'] | null;
  readonly date: CodecTypes['mongo/string@1']['input'] | null;
  readonly coverImg: CodecTypes['mongo/string@1']['input'] | null;
  readonly sourceName: CodecTypes['mongo/string@1']['input'] | null;
  readonly lastError: CodecTypes['mongo/string@1']['input'] | null;
};
export type LinkedArticleOutput = {
  readonly header: CodecTypes['mongo/string@1']['output'];
  readonly content: CodecTypes['mongo/string@1']['output'];
  readonly url: CodecTypes['mongo/string@1']['output'] | null;
  readonly coverImg: CodecTypes['mongo/string@1']['output'] | null;
};
export type LinkedArticleInput = {
  readonly header: CodecTypes['mongo/string@1']['input'];
  readonly content: CodecTypes['mongo/string@1']['input'];
  readonly url: CodecTypes['mongo/string@1']['input'] | null;
  readonly coverImg: CodecTypes['mongo/string@1']['input'] | null;
};
export type TaskPayloadOutput = { readonly id: CodecTypes['mongo/string@1']['output'] | null };
export type TaskPayloadInput = { readonly id: CodecTypes['mongo/string@1']['input'] | null };
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Article: {
      readonly _id: CodecTypes['mongo/string@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'] | null;
      readonly header: CodecTypes['mongo/string@1']['output'];
      readonly url: CodecTypes['mongo/string@1']['output'] | null;
      readonly date: CodecTypes['mongo/string@1']['output'] | null;
      readonly coverImg: CodecTypes['mongo/string@1']['output'] | null;
      readonly sourceName: CodecTypes['mongo/string@1']['output'];
      readonly summaries: SummariesOutput | null;
      readonly linkedArticles: ReadonlyArray<LinkedArticleOutput> | null;
      readonly lastError: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly Bundle: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly sendOn: CodecTypes['mongo/date@1']['output'] | null;
      readonly user: CodecTypes['mongo/objectId@1']['output'];
      readonly newsletters: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
      readonly articles: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
      readonly processingStage: CodecTypes['mongo/int32@1']['output'];
    };
    readonly Newsletter: {
      readonly _id: CodecTypes['mongo/string@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'];
      readonly articles: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
      readonly date: CodecTypes['mongo/string@1']['output'] | null;
      readonly name: CodecTypes['mongo/string@1']['output'] | null;
      readonly url: CodecTypes['mongo/string@1']['output'] | null;
      readonly error: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly Reaction: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly user: CodecTypes['mongo/objectId@1']['output'];
      readonly article: CodecTypes['mongo/string@1']['output'];
      readonly reaction: CodecTypes['mongo/int32@1']['output'];
      readonly date: CodecTypes['mongo/date@1']['output'] | null;
    };
    readonly Task: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly lockedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly data: TaskPayloadOutput | null;
      readonly nextRunAt: CodecTypes['mongo/date@1']['output'] | null;
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly aliasEmail: CodecTypes['mongo/string@1']['output'] | null;
      readonly name: CodecTypes['mongo/string@1']['output'] | null;
      readonly image: CodecTypes['mongo/string@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Article: {
      readonly _id: CodecTypes['mongo/string@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'] | null;
      readonly header: CodecTypes['mongo/string@1']['input'];
      readonly url: CodecTypes['mongo/string@1']['input'] | null;
      readonly date: CodecTypes['mongo/string@1']['input'] | null;
      readonly coverImg: CodecTypes['mongo/string@1']['input'] | null;
      readonly sourceName: CodecTypes['mongo/string@1']['input'];
      readonly summaries: SummariesInput | null;
      readonly linkedArticles: ReadonlyArray<LinkedArticleInput> | null;
      readonly lastError: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly Bundle: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly sendOn: CodecTypes['mongo/date@1']['input'] | null;
      readonly user: CodecTypes['mongo/objectId@1']['input'];
      readonly newsletters: ReadonlyArray<CodecTypes['mongo/string@1']['input']> | null;
      readonly articles: ReadonlyArray<CodecTypes['mongo/string@1']['input']> | null;
      readonly processingStage: CodecTypes['mongo/int32@1']['input'];
    };
    readonly Newsletter: {
      readonly _id: CodecTypes['mongo/string@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'];
      readonly articles: ReadonlyArray<CodecTypes['mongo/string@1']['input']>;
      readonly date: CodecTypes['mongo/string@1']['input'] | null;
      readonly name: CodecTypes['mongo/string@1']['input'] | null;
      readonly url: CodecTypes['mongo/string@1']['input'] | null;
      readonly error: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly Reaction: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly user: CodecTypes['mongo/objectId@1']['input'];
      readonly article: CodecTypes['mongo/string@1']['input'];
      readonly reaction: CodecTypes['mongo/int32@1']['input'];
      readonly date: CodecTypes['mongo/date@1']['input'] | null;
    };
    readonly Task: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly lockedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly data: TaskPayloadInput | null;
      readonly nextRunAt: CodecTypes['mongo/date@1']['input'] | null;
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly aliasEmail: CodecTypes['mongo/string@1']['input'] | null;
      readonly name: CodecTypes['mongo/string@1']['input'] | null;
      readonly image: CodecTypes['mongo/string@1']['input'] | null;
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-namespace';
        readonly entries: {
          readonly collection: {
            readonly articles: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'lastError'; readonly direction: 1 }];
                  readonly sparse: true;
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'sourceName'; readonly direction: 1 },
                    { readonly field: 'date'; readonly direction: -1 },
                    { readonly field: '_id'; readonly direction: 1 },
                  ];
                },
              ];
            };
            readonly bundles: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'processingStage'; readonly direction: 1 },
                    { readonly field: 'sendOn'; readonly direction: 1 },
                    { readonly field: 'user'; readonly direction: 1 },
                    { readonly field: '_id'; readonly direction: -1 },
                  ];
                  readonly unique: true;
                },
              ];
            };
            readonly newsletters: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'error'; readonly direction: 1 }];
                  readonly sparse: true;
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'date'; readonly direction: -1 }];
                },
              ];
            };
            readonly reactions: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'user'; readonly direction: 1 },
                    { readonly field: 'article'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
            };
            readonly tasks: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'name'; readonly direction: 1 },
                    { readonly field: 'lockedAt'; readonly direction: 1 },
                  ];
                  readonly sparse: true;
                },
              ];
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                  readonly partialFilterExpression: {
                    readonly email: { readonly $type: 'string' };
                  };
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'aliasEmail'; readonly direction: 1 }];
                  readonly unique: true;
                  readonly partialFilterExpression: {
                    readonly aliasEmail: { readonly $type: 'string' };
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly articles: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Article';
    };
    readonly newsletters: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Newsletter';
    };
    readonly bundles: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Bundle' };
    readonly reactions: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Reaction';
    };
    readonly tasks: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Task' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Article: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly content: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly header: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly coverImg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly sourceName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly summaries: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Summaries' };
              };
              readonly linkedArticles: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'LinkedArticle' };
                readonly many: true;
              };
              readonly lastError: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'articles' };
          };
          readonly Bundle: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly sendOn: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly user: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly newsletters: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly articles: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly processingStage: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: {
              readonly userRef: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['user'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly newsletterRefs: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Newsletter';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['newsletters'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly articleRefs: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['articles'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'bundles' };
          };
          readonly Newsletter: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly articles: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly date: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly error: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly articleRefs: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['articles'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'newsletters' };
          };
          readonly Reaction: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly user: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly article: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly reaction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly userRef: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['user'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly articleRef: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['article'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'reactions' };
          };
          readonly Task: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly lockedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly data: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'TaskPayload' };
              };
              readonly nextRunAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'tasks' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly aliasEmail: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly valueObjects: {
          readonly Summaries: {
            readonly fields: {
              readonly oneliner: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly overview: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly details: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
          readonly BasicArticle: {
            readonly fields: {
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly header: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly coverImg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly sourceName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly lastError: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
          readonly LinkedArticle: {
            readonly fields: {
              readonly header: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly coverImg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
          readonly TaskPayload: {
            readonly fields: {
              readonly id: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Summaries: {
      readonly fields: {
        readonly oneliner: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly overview: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly details: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly BasicArticle: {
      readonly fields: {
        readonly content: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly header: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly url: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly date: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly coverImg: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly sourceName: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly lastError: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly LinkedArticle: {
      readonly fields: {
        readonly header: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly content: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly url: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly coverImg: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly TaskPayload: {
      readonly fields: {
        readonly id: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
