// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma-next/adapter-mongo/codec-types';
import type { Vector } from '@prisma-next/adapter-mongo/codec-types';

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:3dc942d093b714429d2c735418815d37860c04e151bb78258ab6fa113e8a0141'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:840de65fba7eb950a31487f74ee420b9c21205f38bce58579026747e0264e840'>;

export type CodecTypes = MongoCodecTypes;
export type OperationTypes = Record<string, never>;

export type FieldOutputTypes = {
  readonly Post: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly title: CodecTypes['mongo/string@1']['output'];
    readonly content: CodecTypes['mongo/string@1']['output'] | null;
    readonly authorId: CodecTypes['mongo/objectId@1']['output'];
  };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'] | null;
  };
};
export type FieldInputTypes = {
  readonly Post: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly title: CodecTypes['mongo/string@1']['input'];
    readonly content: CodecTypes['mongo/string@1']['input'] | null;
    readonly authorId: CodecTypes['mongo/objectId@1']['input'];
  };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly email: CodecTypes['mongo/string@1']['input'];
    readonly name: CodecTypes['mongo/string@1']['input'] | null;
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly collections: {
      readonly users: Record<string, never>;
      readonly posts: Record<string, never>;
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Post: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly content: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['authorId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'posts' };
    };
    readonly User: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: 'Post';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['authorId'];
          };
        };
      };
      readonly storage: { readonly collection: 'users' };
    };
  }
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: { readonly users: 'User'; readonly posts: 'Post' };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
