// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma-next/adapter-mongo/codec-types';
import type { Vector } from '@prisma-next/adapter-mongo/codec-types';

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:e174db077d7fa58c3f75c5e6f2ff48ca68012f4741155efce6cf538fb2eed9f5'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:840de65fba7eb950a31487f74ee420b9c21205f38bce58579026747e0264e840'>;

export type CodecTypes = MongoCodecTypes;
export type OperationTypes = Record<string, never>;

export type FieldOutputTypes = {
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly email: CodecTypes['mongo/string@1']['input'];
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly collections: { readonly users: Record<string, never> };
    readonly storageHash: StorageHash;
  },
  {
    readonly User: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'users' };
    };
  }
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: { readonly users: 'User' };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
